// <auto-generated />
using System;
using Bka.TVMazeSraper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bka.TVMazeSraper.Repositories.Migrations
{
    [DbContext(typeof(TVShowContext))]
    [Migration("20180805213753_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bka.TVMazeSraper.Models.Actor", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Bka.TVMazeSraper.Models.ActorTVShow", b =>
                {
                    b.Property<long>("ActorID");

                    b.Property<long>("TVShowID");

                    b.HasKey("ActorID", "TVShowID");

                    b.HasIndex("TVShowID");

                    b.ToTable("ActorsTVShows");
                });

            modelBuilder.Entity("Bka.TVMazeSraper.Models.TVShow", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LastUpdateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("Bka.TVMazeSraper.Models.ActorTVShow", b =>
                {
                    b.HasOne("Bka.TVMazeSraper.Models.Actor", "Actor")
                        .WithMany("ActorsTVShows")
                        .HasForeignKey("ActorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bka.TVMazeSraper.Models.TVShow", "TVShow")
                        .WithMany("ActorsTVShows")
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
